Spring:
  #  swagger 의존성 추가 후 서버 에러
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Diary?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: tiger
  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true #querydsl실행 시 실행되는 jpql 조회
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibername.type:
jwt:
  token:
    secret: 123qweasd345dfdae
    expired-ms: 86400
server:
  port: 8083
